
interface IKisAuth {
    length: number,
    access_token: string,
    token_type: string,
    expires_in: number,
    acess_token_token_expired: string,
}

interface ISectionOutput1 {
    bstp_nmix_hgpr: string,
    bstp_nmix_lwpr: string,
    bstp_nmix_prpr: string,
}

interface IKisSection {
    length: number;
    rt_cd: string,
    msg_cd: string,
    msg1: string,
    output1: ISectionOutput1,
    output2: [],

    stck_bsop_date: string,
    mod_yn: string,
    bstp_nmix_prdy_vrss: string,
    prdy_vrss_sign: string,
    bstp_nmix_prdy_ctrt: string,
    prdy_nmix: string,
    acml_vol: string,
    acml_tr_pbmn: string,
    hts_kor_isnm: string,
    bstp_nmix_prpr: string,
    bstp_cls_code: string,
    prdy_vol: string,
    bstp_nmix_oprc: string,
    bstp_nmix_hgpr: string,
    bstp_nmix_lwpr: string,
    futs_prdy_oprc: string,
    futs_prdy_hgpr: string,
    futs_prdy_lwpr: string,
}

interface IKisAskPrice {
    rt_cd: string,
    msg_cd: string,
    msg1: string,
    output1: IAskPriceOutput1,
    output2: IAskPriceOutput2,
}


interface IAskPriceOutput1 {
    aspr_acpt_hour: string,
    askp1: string,
    askp2: string,
    askp3: string,
    askp4: string,
    askp5: string,
    askp6: string,
    askp7: string,
    askp8: string,
    askp9: string,
    askp10: string,
    bidp1: string,
    bidp2: string,
    bidp3: string,
    bidp4: string,
    bidp5: string,
    bidp6: string,
    bidp7: string,
    bidp8: string,
    bidp9: string,
    bidp10: string,
    askp_rsqn1: string,
    askp_rsqn2: string,
    askp_rsqn3: string,
    askp_rsqn4: string,
    askp_rsqn5: string,
    askp_rsqn6: string,
    askp_rsqn7: string,
    askp_rsqn8: string,
    askp_rsqn9: string,
    askp_rsqn10: string,
    bidp_rsqn1: string,
    bidp_rsqn2: string,
    bidp_rsqn3: string,
    bidp_rsqn4: string,
    bidp_rsqn5: string,
    bidp_rsqn6: string,
    bidp_rsqn7: string,
    bidp_rsqn8: string,
    bidp_rsqn9: string,
    bidp_rsqn10: string,
    askp_rsqn_icdc1: string,
    askp_rsqn_icdc2: string,
    askp_rsqn_icdc3: string,
    askp_rsqn_icdc4: string,
    askp_rsqn_icdc5: string,
    askp_rsqn_icdc6: string,
    askp_rsqn_icdc7: string,
    askp_rsqn_icdc8: string,
    askp_rsqn_icdc9: string,
    askp_rsqn_icdc10: string,
    bidp_rsqn_icdc1: string,
    bidp_rsqn_icdc2: string,
    bidp_rsqn_icdc3: string,
    bidp_rsqn_icdc4: string,
    bidp_rsqn_icdc5: string,
    bidp_rsqn_icdc6: string,
    bidp_rsqn_icdc7: string,
    bidp_rsqn_icdc8: string,
    bidp_rsqn_icdc9: string,
    bidp_rsqn_icdc10: string,
    total_askp_rsqn: string,
    total_bidp_rsqn: string,
    total_askp_rsqn_icdc: string,
    total_bidp_rsqn_icdc: string,
    ovtm_total_askp_icdc: string,
    ovtm_total_bidp_icdc: string,
    ovtm_total_askp_rsqn: string,
    ovtm_total_bidp_rsqn: string,
    ntby_aspr_rsqn: string,
    new_mkop_cls_code: string,
}

interface IAskPriceOutput2 {
    antc_mkop_cls_code: string,
    stck_prpr: string,
    stck_oprc: string,
    stck_hgpr: string,
    stck_lwpr: string,
    stck_sdpr: string,
    antc_cnpr: string,
    antc_cntg_vrss_sign: string,
    antc_cntg_vrss: string,
    antc_cntg_prdy_ctrt: string,
    antc_vol: string,
    stck_shrn_iscd: string,
    vi_cls_code: string,
}

interface IKisDaily {
    rt_cd: string,
    msg_cd: string,
    msg1: string,
    output1: IKisDailyOutput1,
    output2: IKisDailyOutput2[],
}

interface IKisDailyOutput1 {
    prdy_vrss: string,
    prdy_vrss_sign: string,
    prdy_ctrt: string,
    stck_prdy_clpr: string,
    acml_vol: string,
    acml_tr_pbmn: string,
    hts_kor_isnm: string,
    stck_prpr: string,
    stck_shrn_iscd: string,
    prdy_vol: string,
    stck_mxpr: string,
    stck_llam: string,
    stck_oprc: string,
    stck_hgpr: string,
    stck_lwpr: string,
    stck_prdy_oprc: string,
    stck_prdy_hgpr: string,
    stck_prdy_lwpr: string,
    askp: string,
    bidp: string,
    prdy_vrss_vol: string,
    vol_tnrt: string,
    stck_fcam: string,
    lstn_stcn: string,
    cpfn: string,
    hts_avls: string,
    per: string,
    eps: string,
    pbr: string,
    "itewhol_loan_rmnd_ratem name": string,
}
interface IKisDailyOutput2 {
    stck_bsop_date: string,
    stck_clpr: string,
    stck_oprc: string,
    stck_hgpr: string,
    stck_lwpr: string,
    acml_vol: string,
    acml_tr_pbmn: string,
    flng_cls_code: string,
    prtt_rate: string,
    mod_yn: string,
    prdy_vrss_sign: string,
    prdy_vrss: string,
    revl_issu_reas: string,
}

interface IKisNow {
    rt_cd: string,
    msg_cd: string,
    msg1: string,
    output: IKisNowOutput,
   
}
interface IKisNowOutput {
    iscd_stat_cls_code: string,
    marg_rat: string,
    rprs_mrkt_kor_name: string,
    new_hgpr_lwpr_cls_code: string,
    bstp_kor_isnm: string,
    temp_stop_yn: string,
    oprc_rang_cont_yn: string,
    clpr_rang_cont_yn: string,
    crdt_able_yn: string,
    grmn_rate_cls_code: string,
    elw_pblc_yn: string,
    stck_prpr: string,
    prdy_vrss: string,
    prdy_vrss_sign: string,
    prdy_ctrt: string,
    acml_tr_pbmn: string,
    acml_vol: string,
    prdy_vrss_vol_rate: string,
    stck_oprc: string,
    stck_hgpr: string,
    stck_lwpr: string,
    stck_mxpr: string,
    stck_llam: string,
    stck_sdpr: string,
    wghn_avrg_stck_prc: string,
    hts_frgn_ehrt: string,
    frgn_ntby_qty: string,
    pgtr_ntby_qty: string,
    pvt_scnd_dmrs_prc: string,
    pvt_frst_dmrs_prc: string,
    pvt_pont_val: string,
    pvt_frst_dmsp_prc: string,
    pvt_scnd_dmsp_prc: string,
    dmrs_val: string,
    dmsp_val: string,
    cpfn: string,
    rstc_wdth_prc: string,
    stck_fcam: string,
    stck_sspr: string,
    aspr_unit: string,
    hts_deal_qty_unit_val: string,
    lstn_stcn: string,
    hts_avls: string,
    per: string,
    pbr: string,
    stac_month: string,
    vol_tnrt: string,
    eps: string,
    bps: string,
    d250_hgpr: string,
    d250_hgpr_date: string,
    d250_hgpr_vrss_prpr_rate: string,
    d250_lwpr: string,
    d250_lwpr_date: string,
    d250_lwpr_vrss_prpr_rate: string,
    stck_dryy_hgpr: string,
    dryy_hgpr_vrss_prpr_rate: string,
    dryy_hgpr_date: string,
    stck_dryy_lwpr: string,
    dryy_lwpr_vrss_prpr_rate: string,
    dryy_lwpr_date: string,
    w52_hgpr: string,
    w52_hgpr_vrss_prpr_ctrt: string,
    w52_hgpr_date: string,
    w52_lwpr: string,
    w52_lwpr_vrss_prpr_ctrt: string,
    w52_lwpr_date: string,
    whol_loan_rmnd_rate: string,
    ssts_yn: string,
    stck_shrn_iscd: string,
    fcam_cnnm: string,
    cpfn_cnnm: string,
    apprch_rate: string,
    frgn_hldn_qty: string,
    vi_cls_code: string,
    ovtm_vi_cls_code: string,
    last_ssts_cntg_qty: string,
    invt_caful_yn: string,
    mrkt_warn_cls_code: string,
    short_over_yn: string,
    sltr_yn: string,
}